# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-21 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20180721_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='checked_by',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='Inspector'),
        ),
    ]
